"""
frame_instances.py (generated)
"""
population = [
    {"Name": "default", "Sheet": "letter", "Orientation": "landscape"},
    {"Name": "default", "Sheet": "letter", "Orientation": "portrait"},
    {"Name": "default", "Sheet": "tabloid", "Orientation": "landscape"},
    {"Name": "default", "Sheet": "tabloid", "Orientation": "portrait"},
    {"Name": "default", "Sheet": "C", "Orientation": "landscape"},
    {"Name": "default", "Sheet": "C", "Orientation": "portrait"},
    {"Name": "default", "Sheet": "D", "Orientation": "landscape"},
    {"Name": "default", "Sheet": "D", "Orientation": "portrait"},
    {"Name": "default", "Sheet": "E", "Orientation": "landscape"},
    {"Name": "default", "Sheet": "E", "Orientation": "portrait"},
    {"Name": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape"},
    {"Name": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait"},
    {"Name": "TRI MBSE", "Sheet": "tabloid", "Orientation": "landscape"},
    {"Name": "TRI MBSE", "Sheet": "tabloid", "Orientation": "portrait"},
    {"Name": "TRI MBSE", "Sheet": "C", "Orientation": "landscape"},
    {"Name": "TRI MBSE", "Sheet": "C", "Orientation": "portrait"},
    {"Name": "TRI MBSE", "Sheet": "D", "Orientation": "landscape"},
    {"Name": "TRI MBSE", "Sheet": "D", "Orientation": "portrait"},
    {"Name": "TRI MBSE", "Sheet": "E", "Orientation": "landscape"},
    {"Name": "TRI MBSE", "Sheet": "E", "Orientation": "portrait"},
    {"Name": "Mint Open", "Sheet": "letter", "Orientation": "landscape"},
    {"Name": "Mint Open", "Sheet": "letter", "Orientation": "portrait"},
    {"Name": "Mint Open", "Sheet": "tabloid", "Orientation": "landscape"},
    {"Name": "Mint Open", "Sheet": "tabloid", "Orientation": "portrait"},
    {"Name": "Mint Open", "Sheet": "C", "Orientation": "landscape"},
    {"Name": "Mint Open", "Sheet": "C", "Orientation": "portrait"},
    {"Name": "Mint Open", "Sheet": "D", "Orientation": "landscape"},
    {"Name": "Mint Open", "Sheet": "D", "Orientation": "portrait"},
    {"Name": "Mint Open", "Sheet": "E", "Orientation": "landscape"},
    {"Name": "Mint Open", "Sheet": "E", "Orientation": "portrait"},
]
