"""
open_field_instances.py (generated)
"""
population = [
    {"Metadata": "Title", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 8, "y position": 202, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 8, "y position": 31, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 5, "y position": 4, "max width": 180, "max height": 24},
    {"Metadata": "Author", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 280, "y position": 22, "max width": 20, "max height": 5},
    {"Metadata": "Modification date", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 18, "max width": 20, "max height": 5},
    {"Metadata": "Document ID", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 14, "max width": 20, "max height": 5},
    {"Metadata": "Version", "Frame": "default", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 10, "max width": 20, "max height": 5},
    {"Metadata": "Title", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 8, "y position": 265, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 10, "y position": 31, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 8, "y position": 5, "max width": 180, "max height": 24},
    {"Metadata": "Author", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 22, "max width": 20, "max height": 5},
    {"Metadata": "Modification date", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 18, "max width": 20, "max height": 5},
    {"Metadata": "Document ID", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 14, "max width": 20, "max height": 5},
    {"Metadata": "Version", "Frame": "default", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 10, "max width": 20, "max height": 5},
    {"Metadata": "Title", "Frame": "default", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 264, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 28, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 9, "max width": 180, "max height": 24},
    {"Metadata": "Title", "Frame": "default", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 10, "y position": 415, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 8, "y position": 25, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 5, "y position": 10, "max width": 180, "max height": 24},
    {"Metadata": "Title", "Frame": "default", "Sheet": "C", "Orientation": "landscape",
     "x position": 15, "y position": 440, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "C", "Orientation": "landscape",
     "x position": 157, "y position": 30, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "C", "Orientation": "landscape",
     "x position": 15, "y position": 30, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "default", "Sheet": "C", "Orientation": "portrait",
     "x position": 18, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "C", "Orientation": "portrait",
     "x position": 400, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "C", "Orientation": "portrait",
     "x position": 19, "y position": 18, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "default", "Sheet": "D", "Orientation": "landscape",
     "x position": 19, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "D", "Orientation": "landscape",
     "x position": 400, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "D", "Orientation": "landscape",
     "x position": 19, "y position": 38, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "default", "Sheet": "D", "Orientation": "portrait",
     "x position": 18, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "D", "Orientation": "portrait",
     "x position": 400, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "D", "Orientation": "portrait",
     "x position": 19, "y position": 18, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "default", "Sheet": "E", "Orientation": "landscape",
     "x position": 30, "y position": 884, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "E", "Orientation": "landscape",
     "x position": 500, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "E", "Orientation": "landscape",
     "x position": 30, "y position": 38, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "default", "Sheet": "E", "Orientation": "portrait",
     "x position": 30, "y position": 1180, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "default", "Sheet": "E", "Orientation": "portrait",
     "x position": 220, "y position": 30, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "default", "Sheet": "E", "Orientation": "portrait",
     "x position": 30, "y position": 30, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 8, "y position": 202, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 8, "y position": 31, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 5, "y position": 4, "max width": 180, "max height": 24},
    {"Metadata": "Author", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 280, "y position": 22, "max width": 20, "max height": 5},
    {"Metadata": "Modification date", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 18, "max width": 20, "max height": 5},
    {"Metadata": "Document ID", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 14, "max width": 20, "max height": 5},
    {"Metadata": "Version", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 10, "max width": 20, "max height": 5},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 8, "y position": 265, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 10, "y position": 31, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 8, "y position": 5, "max width": 180, "max height": 24},
    {"Metadata": "Author", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 22, "max width": 20, "max height": 5},
    {"Metadata": "Modification date", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 18, "max width": 20, "max height": 5},
    {"Metadata": "Document ID", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 14, "max width": 20, "max height": 5},
    {"Metadata": "Version", "Frame": "TRI MBSE", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 10, "max width": 20, "max height": 5},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 264, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 28, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 9, "max width": 180, "max height": 24},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 10, "y position": 415, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 8, "y position": 25, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 5, "y position": 10, "max width": 180, "max height": 24},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "C", "Orientation": "landscape",
     "x position": 15, "y position": 440, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "C", "Orientation": "landscape",
     "x position": 157, "y position": 30, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "C", "Orientation": "landscape",
     "x position": 15, "y position": 30, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "C", "Orientation": "portrait",
     "x position": 18, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "C", "Orientation": "portrait",
     "x position": 400, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "C", "Orientation": "portrait",
     "x position": 19, "y position": 18, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "D", "Orientation": "landscape",
     "x position": 19, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "D", "Orientation": "landscape",
     "x position": 400, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "D", "Orientation": "landscape",
     "x position": 19, "y position": 38, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "D", "Orientation": "portrait",
     "x position": 18, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "D", "Orientation": "portrait",
     "x position": 400, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "D", "Orientation": "portrait",
     "x position": 19, "y position": 18, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "E", "Orientation": "landscape",
     "x position": 30, "y position": 884, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "E", "Orientation": "landscape",
     "x position": 500, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "E", "Orientation": "landscape",
     "x position": 30, "y position": 38, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "TRI MBSE", "Sheet": "E", "Orientation": "portrait",
     "x position": 30, "y position": 1180, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "TRI MBSE", "Sheet": "E", "Orientation": "portrait",
     "x position": 220, "y position": 30, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "TRI MBSE", "Sheet": "E", "Orientation": "portrait",
     "x position": 30, "y position": 30, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 8, "y position": 202, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 10, "y position": 31, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 10, "y position": 0, "max width": 180, "max height": 24},
    {"Metadata": "Author", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 22, "max width": 20, "max height": 5},
    {"Metadata": "Modification date", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 18, "max width": 20, "max height": 5},
    {"Metadata": "Document ID", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 14, "max width": 20, "max height": 5},
    {"Metadata": "Version", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "landscape",
     "x position": 230, "y position": 10, "max width": 20, "max height": 5},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 8, "y position": 265, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 10, "y position": 31, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 10, "y position": 0, "max width": 180, "max height": 24},
    {"Metadata": "Author", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 22, "max width": 20, "max height": 5},
    {"Metadata": "Modification date", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 18, "max width": 20, "max height": 5},
    {"Metadata": "Document ID", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 14, "max width": 20, "max height": 5},
    {"Metadata": "Version", "Frame": "Mint Open", "Sheet": "letter", "Orientation": "portrait",
     "x position": 170, "y position": 10, "max width": 20, "max height": 5},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 264, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 25, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "landscape",
     "x position": 8, "y position": 9, "max width": 180, "max height": 24},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 10, "y position": 415, "max width": 254, "max height": 13},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 8, "y position": 30, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "portrait",
     "x position": 10, "y position": 5, "max width": 180, "max height": 24},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "C", "Orientation": "landscape",
     "x position": 19, "y position": 440, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "C", "Orientation": "landscape",
     "x position": 19, "y position": 65, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "C", "Orientation": "landscape",
     "x position": 19, "y position": 15, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "C", "Orientation": "portrait",
     "x position": 15, "y position": 590, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "C", "Orientation": "portrait",
     "x position": 19, "y position": 70, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "C", "Orientation": "portrait",
     "x position": 19, "y position": 18, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "D", "Orientation": "landscape",
     "x position": 19, "y position": 584, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "D", "Orientation": "landscape",
     "x position": 330, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "D", "Orientation": "landscape",
     "x position": 19, "y position": 38, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "D", "Orientation": "portrait",
     "x position": 19, "y position": 890, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "D", "Orientation": "portrait",
     "x position": 19, "y position": 70, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "D", "Orientation": "portrait",
     "x position": 19, "y position": 18, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "E", "Orientation": "landscape",
     "x position": 30, "y position": 884, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "E", "Orientation": "landscape",
     "x position": 500, "y position": 38, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "E", "Orientation": "landscape",
     "x position": 30, "y position": 38, "max width": 191, "max height": 25},
    {"Metadata": "Title", "Frame": "Mint Open", "Sheet": "E", "Orientation": "portrait",
     "x position": 30, "y position": 1180, "max width": 254, "max height": 25},
    {"Metadata": "Copyright notice", "Frame": "Mint Open", "Sheet": "E", "Orientation": "portrait",
     "x position": 340, "y position": 30, "max width": 254, "max height": 57},
    {"Metadata": "Organization logo", "Frame": "Mint Open", "Sheet": "E", "Orientation": "portrait",
     "x position": 30, "y position": 30, "max width": 191, "max height": 25},
]
