"""
titleblock_placement_instances.py (generated)
"""
population = [
    {"Frame": "Default", "Sheet": "tabloid", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "medium", "X": 275, "Y": 9},
    {"Frame": "Default", "Sheet": "tabloid", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "medium", "X": 150, "Y": 9},
    {"Frame": "Default", "Sheet": "C", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 460, "Y": 15},
    {"Frame": "Default", "Sheet": "C", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 300, "Y": 15},
    {"Frame": "Default", "Sheet": "D", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 753, "Y": 38},
    {"Frame": "Default", "Sheet": "D", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 553, "Y": 38},
    {"Frame": "Default", "Sheet": "E", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 1025, "Y": 38},
    {"Frame": "Default", "Sheet": "E", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 740, "Y": 25},
    {"Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "medium", "X": 275, "Y": 9},
    {"Frame": "TRI MBSE", "Sheet": "tabloid", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "medium", "X": 150, "Y": 9},
    {"Frame": "TRI MBSE", "Sheet": "C", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 460, "Y": 15},
    {"Frame": "TRI MBSE", "Sheet": "C", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 300, "Y": 15},
    {"Frame": "TRI MBSE", "Sheet": "D", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 753, "Y": 38},
    {"Frame": "TRI MBSE", "Sheet": "D", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 553, "Y": 38},
    {"Frame": "TRI MBSE", "Sheet": "E", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 1025, "Y": 38},
    {"Frame": "TRI MBSE", "Sheet": "E", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 740, "Y": 25},
    {"Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "medium", "X": 300, "Y": 9},
    {"Frame": "Mint Open", "Sheet": "tabloid", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "medium", "X": 150, "Y": 8},
    {"Frame": "Mint Open", "Sheet": "C", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 453, "Y": 15},
    {"Frame": "Mint Open", "Sheet": "C", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 300, "Y": 15},
    {"Frame": "Mint Open", "Sheet": "D", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 753, "Y": 38},
    {"Frame": "Mint Open", "Sheet": "D", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 450, "Y": 18},
    {"Frame": "Mint Open", "Sheet": "E", "Orientation": "landscape",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 1025, "Y": 38},
    {"Frame": "Mint Open", "Sheet": "E", "Orientation": "portrait",
     "Title block pattern": "SE Simple", "Sheet size group": "large", "X": 740, "Y": 25},
]
